version: "2"
services:
  nginx:
    build: ./docker_config/nginx
    ports:
      - "88:80"
    volumes:
      - ./docker_config/chat.conf:/var/www/gateway
      - ./docker_config/docker_sockets:/run/docker_sockets
  ruby:
    build: ./docker_config/ruby
    volumes:
      - ./chat:/var/www/chat
      - ./chat/vendor/bundle:/usr/local/bundle
      - ./docker_config/docker_sockets:/run/docker_sockets
#    links:
#      - db
#      - redis
#  db:
#    build: ./db
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: foR1980
#      MYSQL_DATABASE: helpdesk
#    volumes:
#      - db:/var/lib/mysql
#      - ./docker_sockets:/run/docker_sockets
#  redis:
#    image: redis:3.2
#    ports:
#      - "6379:6379"
#volumes:
#  db: