version: "2"
services:
  nginx:
    build: ./docker_config/nginx
    ports:
      - "88:80"
    volumes:
      - ./docker_config/docker_sockets:/run/docker_sockets
  ruby:
    build: ./docker_config/ruby
    volumes:
      - ./chat:/var/www/chat
      - ./chat/vendor/bundle:/usr/local/bundle
      - ./docker_config/docker_sockets:/run/docker_sockets
#    links:
#      - db
#      - redis
  db:
    build: ./docker_config/db
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: asdasd
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker_config/docker_sockets:/run/docker_sockets
#  redis:
#    image: redis:3.2
#    ports:
#      - "6379:6379"
volumes:
  pgdata: