version: "2"
services:
  nginx:
    build: ./docker_config/nginx
    ports:
      - "88:80"
    volumes:
      - ./docker_config/docker_sockets:/run/docker_sockets
  web:
    build: ./docker_config/web
    tty: true # for interactive mode
    stdin_open: true # for interactive mode
    volumes:
      - ./chat:/var/www/chat
      - ./chat/vendor/bundle:/usr/local/bundle
      - ./docker_config/docker_sockets:/run/docker_sockets
    links:
      - redis
    depends_on:
      - db
      - redis
  sidekiq:
    build: ./docker_config/sidekiq
    depends_on:
      - db
      - redis
      - web
    volumes:
      - ./chat:/var/www/chat
      - ./chat/vendor/bundle:/usr/local/bundle
    links:
      - redis
  db:
    build: ./docker_config/db
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: asdasd
      POSTGRES_DB: chat
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker_config/docker_sockets:/run/docker_sockets
  redis:
    image: redis:3.2
volumes:
  pgdata: